# Load essential packages
library(readr)
library(dplyr)

# Read in the CSV file
complete_drafts <- read_csv("C:/Users/lucas/Downloads/NBA_Draft_Project/2004-2024_drafts.csv", 
                       col_types = cols(Pk = col_character()))


# Notice how none of the rows include the  year drafted, so I will add that using the following code: 

# Create the vector of years, repeated 60 times each
Years <- rep(2024:2004, each = 60)  
length(Years) == nrow(complete_drafts) 

# Add the year column
complete_drafts$Year <- Years

# Save the new CSV with the year column
complete_drafts <- complete_drafts |>
  select(Year, everything())  # Move Year to the first column

# Replace outdated team abbreviations
complete_drafts$Tm[complete_drafts$Tm == "CHA"] <- "CHO"
complete_drafts$Tm[complete_drafts$Tm == "NOH" | complete_drafts$Tm == "NOK"] <- "NOP"
complete_drafts$Tm[complete_drafts$Tm == "SEA"] <- "OKC"
complete_drafts$Tm[complete_drafts$Tm == "NJN"] <- "BRK"


# Draft-night / pre-season trades; couldn't figure out how to have R do this manually resorted to forcing
## ChatGPT to identify the changes itself, then manually code said changes
manual_fixes <- tribble(
  ~Player,              ~Correct_Tm,
  "Devin Harris",       "DAL",
  "Luol Deng",          "CHI",
  "Jameer Nelson",      "ORL",
  "Pavel Podkolzin",    "DAL",
  "Viktor Khryapa",     "POR",
  "Nate Robinson",           "NYK",  
  "Jarrett Jack",            "POR",  
  "Linas Kleiza",            "DEN",  
  "Martynas Andriuškevičius", "CLE", 
  "Dijon Thompson",          "PHO",  
  "Lawrence Roberts",        "MEM",  
  "Marcin Gortat",           "ORL",
  "LaMarcus Aldridge", "POR",
  "Tyrus Thomas",      "CHI",
  "Brandon Roy",       "POR",
  "Randy Foye",        "MIN",
  "Rudy Gay",          "MEM",
  "Thabo Sefolosha",   "CHI",
  "Rodney Carney",     "PHI",
  "Rajon Rondo",       "BOS",
  "Sergio Rodríguez",  "POR",
  "James White",       "SAS",
  "Bobby Jones",       "PHI",
  "Alexander Johnson", "MEM",
  "Leon Powe",         "BOS",
  "Cheikh Samb",       "DET",
  "Damir Markota",     "MIL",
  "Jeff Green",         "OKC",  
  "Brandan Wright",     "GSW",  
  "Jason Smith",        "PHI",  
  "Daequan Cook",       "MIA",  
  "Rudy Fernández",     "POR",  
  "Carl Landry",        "HOU",  
  "Glen Davis",         "BOS",  
  "Jermareo Davidson",  "CHO",  
  "Kyrylo Fesenko",     "UTA",  
  "Derrick Byars",      "SAS",
  "O.J. Mayo",        "MEM",
  "Kevin Love",       "MIN",
  "Jerryd Bayless",   "POR",
  "Brandon Rush",     "IND",
  "Roy Hibbert",      "IND",
  "Nicolas Batum",    "POR",
  "Darrell Arthur",   "MEM",
  "Donte Greene",     "SAC",
  "D.J. White",       "OKC",
  "Walter Sharpe",    "DET",
  "Joey Dorsey",      "HOU",
  "Mario Chalmers",   "MIA",
  "Goran Dragić",     "PHO",
  "Nathan Jawai",     "TOR",
  "Ty Lawson",         "DEN",
  "Byron Mullens",     "OKC",
  "Rodrigue Beaubois", "DAL",
  "Toney Douglas",     "NYK",
  "Jeff Pendergraph",  "POR",
  "Jermaine Taylor",   "HOU",
  "Jon Brockman",      "SAC",
  "Patrick Beverley",  "HOU",
  "Marcus Thornton",   "NOP",
  "Chase Budinger",    "HOU",
  "Nick Calathes",     "MEM",
  "Cole Aldrich",       "OKC",
  "Craig Brackins",     "PHI",
  "Quincy Pondexter",   "NOP",
  "Luke Babbitt",       "POR",
  "Kevin Seraphin",     "WAS",
  "Eric Bledsoe",       "LAC",
  "Trevor Booker",      "WAS",
  "Hamady N'Diaye",     "WAS",
  "Lazar Hayward",      "MIN",
  "Nemanja Bjelica",    "MIN",
  "Damion James",       "BRK",
  "Jordan Crawford",    "ATL",
  "Dominique Jones",    "DAL",
  "Solomon Alabi",      "TOR",
  "Jerome Jordan",      "NYK",
  "Ryan Reid",          "OKC",
  "Tibor Pleiß",        "UTA",
  "Bismack Biyombo",   "CHO",   
  "Jimmer Fredette",   "SAC",   
  "Kawhi Leonard",     "SAS",   
  "Tobias Harris",     "MIL",   
  "Donatas Motiejūnas","HOU",   
  "Nikola Mirotić",    "CHI",   
  "MarShon Brooks",    "BRK",   
  "Jordan Hamilton",   "DEN",   
  "JaJuan Johnson",    "BOS",   
  "Norris Cole",       "MIA",   
  "Bojan Bogdanović",  "BRK",   
  "Justin Harper",     "ORL",   
  "Jeremy Tyler",      "GSW",   
  "Dāvis Bertāns",     "SAS",   
  "Malcolm Lee",       "MIN",   
  "Josh Harrellson",   "NYK",
  "Jeremy Lamb",          "OKC",
  "Maurice Harkless",     "ORL",
  "Royce White",          "SAC",
  "Tyler Zeller",         "CLE",
  "Jared Cunningham",     "DAL",
  "Arnett Moultrie",      "PHI",
  "Bernard James",        "DAL",
  "Jae Crowder",          "DAL",
  "Orlando Johnson",      "IND",
  "Tyshawn Taylor",       "BRK",
  "Justin Hamilton",      "MIA",
  "Kostas Papanikolaou",  "HOU",
  "Tornike Shengelia",    "BRK",
  "Darius Johnson-Odom",  "LAL",
  "Furkan Aldemir",       "PHI",
  "Nerlens Noel",       "PHI",
  "Trey Burke",         "UTA",
  "Kelly Olynyk",       "BOS",
  "Shabazz Muhammad",   "MIN",
  "Lucas Nogueira",     "TOR",
  "Shane Larkin",       "DAL",
  "Gorgui Dieng",       "MIN",
  "Andre Roberson",     "OKC",
  "Rudy Gobert",        "UTA",
  "Archie Goodwin",     "PHO",
  "Nemanja Nedović",    "GSW",
  "Allen Crabbe",       "POR",
  "Glen Rice Jr.",      "WAS",
  "Nate Wolters",       "MIL",
  "Jeff Withey",        "NOP",
  "Grant Jerrett",      "OKC",
  "Pierre Jackson",     "DAL",
  "Ricky Ledo",        "DAL",
  "Mike Muscala",       "ATL",
  "Erick Green",        "DEN",
  "Raul Neto",          "UTA",
  "James Ennis",        "MIA",
  "Joffrey Lauvergne",  "DEN",
  "Lorenzo Brown",      "PHI",
  "Andrew Wiggins",     "MIN",
  "Elfrid Payton",      "ORL",
  "Doug McDermott",     "CHI",
  "Dario Šarić",        "PHI",
  "Jusuf Nurkić",       "DEN",
  "Gary Harris",        "DEN",
  "Shabazz Napier",     "MIA",
  "P.J. Hairston",      "CHO",
  "Bogdan Bogdanović",  "SAC",
  "Jarnell Stokes",     "MEM",
  "Markel Brown",       "BRK",
  "Dwight Powell",      "BOS",
  "Jordan Clarkson",    "LAL",
  "Russ Smith",         "NOP",
  "Lamar Patterson",    "ATL",
  "Semaj Christon",     "OKC",
  "Devyn Marble",       "ORL",
  "Jordan McRae",       "PHO",
  "Cory Jefferson",     "BRK",
  "Kelly Oubre Jr.",         "WAS",
  "Jerian Grant",            "NYK",
  "Rondae Hollis-Jefferson", "BRK",
  "Tyus Jones",              "MIN",
  "Cedi Osman",              "CLE",
  "Rakeem Christmas",        "IND",
  "Willy Hernangómez",       "NYK",
  "Pat Connaughton",         "POR",
  "Norman Powell",           "TOR",
  "Andrew Harrison",         "MEM",
  "Branden Dawson",          "LAC",
  "Marquese Chriss",    "PHO",
  "Domantas Sabonis",   "OKC",
  "Taurean Prince",     "ATL",
  "Georgios Papagiannis","SAC",
  "Caris LeVert",       "BRK",
  "Malachi Richardson", "SAC",
  "Skal Labissière",    "SAC",
  "Deyonta Davis",      "MEM",
  "Cheick Diallo",      "NOP",
  "Patrick McCaw",      "GSW",
  "Diamond Stone",      "LAC",
  "Isaiah Whitehead",   "BRK",
  "Jake Layman",        "POR",
  "Kay Felder",         "CLE",
  "Daniel Hamilton",    "OKC",
  "Lauri Markkanen",       "CHI",
  "Zach Collins",          "POR",
  "Donovan Mitchell",      "UTA",
  "Justin Jackson",        "SAC",
  "Justin Patton",         "MIN",
  "Tyler Lydon",           "DEN",
  "Anžejs Pasečņiks",      "WAS",
  "Kyle Kuzma",            "LAL",
  "Tony Bradley",          "UTA",
  "Harry Giles",           "SAC",
  "Josh Hart",             "LAL",
  "Frank Jackson",         "NOP",
  "Ivan Rabb",             "MEM",
  "Jordan Bell",           "GSW",
  "Jawun Evans",           "LAC",
  "Dwayne Bacon",          "CHO",
  "Thomas Bryant",         "LAL",
  "Dillon Brooks",         "MEM",
  "Sterling Brown",        "MIL",
  "Sindarius Thornwell",   "LAC",
  "Edmond Sumner",         "IND",
  "Luka Dončić",              "DAL",
  "Trae Young",               "ATL",
  "Mikal Bridges",            "PHO",
  "Shai Gilgeous-Alexander",  "LAC",
  "Miles Bridges",            "CHO",
  "Zhaire Smith",             "PHI",
  "Devonte' Graham",          "CHO",
  "Gary Trent Jr.",           "POR",
  "Khyri Thomas",             "DET",
  "Isaac Bonga",              "LAL",
  "Jarred Vanderbilt",        "DEN",
  "Justin Jackson",           "ORL",
  "Hamidou Diallo",           "OKC",
  "De'Anthony Melton",        "PHO",
  "Vince Edwards",            "HOU",
  "Shake Milton",             "PHI",
  "Ray Spalding",             "PHO",
  "Kostas Antetokounmpo",     "DAL",
  "De'Andre Hunter",          "ATL",
  "Jarrett Culver",           "MIN",
  "Jaxson Hayes",             "NOP",
  "Cameron Johnson",          "PHO",
  "Nickeil Alexander-Walker", "NOP",
  "Matisse Thybulle",         "PHI",
  "Brandon Clarke",           "MEM",
  "Darius Bazley",            "OKC",
  "Ty Jerome",                "PHO",
  "Mfiondu Kabengele",        "LAC",
  "Kevin Porter Jr.",         "CLE",
  "KZ Okpala",                "MIA",
  "Carsen Edwards",           "BOS",
  "Bruno Fernando",           "ATL",
  "Didi Louzada",             "NOP",
  "Deividas Sirvydis",        "DET",
  "Alen Smailagić",           "GSW",
  "Admiral Schofield",        "WAS",
  "Bol Bol",                  "DEN",
  "Isaiah Roby",              "OKC",
  "Talen Horton-Tucker",      "LAL",
  "Ignas Brazdeikis",         "NYK",
  "Jarrell Brantley",         "UTA",
  "Kyle Guy",                 "SAC",
  "Jordan Bone",              "DET",
  "Miye Oni",                 "UTA",
  "Isaiah Stewart",     "DET",
  "Aleksej Pokusevski", "OKC",
  "Saddiq Bey",         "DET",
  "Leandro Bolmaro",    "MIN",
  "RJ Hampton",         "DEN",
  "Immanuel Quickley",  "NYK",
  "Jaden McDaniels",    "MIN",
  "Desmond Bane",       "MEM",
  "Daniel Oturu",       "LAC",
  "Théo Maledon",       "OKC",
  "Xavier Tillman Sr.", "MEM",
  "Tyler Bey",          "DAL",
  "Vit Krejci",         "OKC",
  "Saben Lee",          "DET",
  "Robert Woodard II",  "SAC",
  "Elijah Hughes",      "UTA",
  "Nick Richards",      "CHO",
  "Kenyon Martin Jr.",  "HOU",
  "Cassius Winston",    "WAS",
  "Jay Scrubb",         "LAC",
  "Reggie Perry",       "BRK",
  "Sam Merrill",        "MIL",
  "Ziaire Williams",          "MEM",
  "Alperen Şengün",           "HOU",
  "Trey Murphy III",          "NOP",
  "Kai Jones",                "CHO",
  "Keon Johnson",             "LAC",
  "Isaiah Jackson",           "IND",
  "Day'Ron Sharpe",           "BRK",
  "Santi Aldama",             "MEM",
  "Isaiah Todd",              "WAS",
  "Jeremiah Robinson-Earl",   "OKC",
  "Jason Preston",            "LAC",
  "Brandon Boston Jr.",          "LAC",
  "Miles McBride",            "NYK",
  "JT Thor",                  "CHO",
  "Jared Butler",             "UTA",
  "Greg Brown",               "POR",
  "Sandro Mamukelashvili",    "MIL",
  "Georgios Kalaitzakis",     "MIL",
  "Ousmane Dieng",         "OKC",
  "Jalen Duren",           "DET",
  "Ochai Agbaji",          "UTA",
  "Jake LaRavia",          "MEM",
  "Walker Kessler",        "UTA",
  "David Roddy",           "MEM",
  "Wendell Moore Jr.",     "MIN",
  "TyTy Washington Jr.",   "HOU",
  "Peyton Watson",         "DEN",
  "Jaden Hardy",           "DAL",
  "Kennedy Chandler",      "MEM",
  "Bryce McGowens",        "CHO",
  "Ryan Rollins",          "GSW",
  "Josh Minott",           "MIN",
  "Kendall Brown",         "IND",
  "Tyrese Martin",         "ATL",
  "Bilal Coulibaly",         "WAS",
  "Jarace Walker",           "IND",
  "Cason Wallace",           "OKC",
  "Dereck Lively II",        "DAL",
  "Olivier-Maxence Prosper", "DAL",
  "Marcus Sasser",           "DET",
  "Julian Strawther",        "DEN",
  "Leonard Miller",          "MIN",
  "Colby Jones",             "SAC",
  "Jalen Pickett",           "DEN",
  "Julian Phillips",         "CHI",
  "Andre Jackson Jr.",       "MIL",
  "Hunter Tyson",            "DEN",
  "Jordan Walsh",            "BOS",
  "Mouhamed Gueye",          "ATL",
  "Maxwell Lewis",           "LAL",
  "Trayce Jackson-Davis",    "GSW",
  "Rob Dillingham",    "MIN",   
  "Bub Carrington",    "WAS",   
  "DaRon Holmes",   "DEN",   
  "Ryan Dunn",         "PHO",   
  "Kyshawn George",    "WAS",   
  "Dillon Jones",      "OKC",  
  "Tyler Kolek",       "NYK",   
  "Johnny Furphy",     "IND",   
  "Bobi Klintman",     "DET",   
  "Ajay Mitchell",     "OKC",   
  "Oso Ighodaro",      "PHO",   
  "Cam Spencer",       "MEM",
  "Marc Gasol",        "MEM"
)

# Left-join master fixes table onto drafts DF
drafts_fixed <- complete_drafts |>
  left_join(manual_fixes, by = "Player")

drafts_fixed <- drafts_fixed |>
  mutate(
    Tm = coalesce(Correct_Tm, Tm)
  )

# Dropping the helper column so I'm back to  original schema
drafts_fixed <- drafts_fixed |>
  select(-Correct_Tm)

# Exporting the updated CSV file
readr::write_csv(drafts_fixed, "2004-2024_drafts_with_year_and_updated_teams.csv")